### ISSUE TITLE
Button failure

### ISSUE THREAD

**Issue by SMSshuai** [gitbito/bitoai#170]
Click "Enable/Disable This" and there is no response。
![image](https://github.com/gitbito/bitoai/assets/66891829/de405e18-8cdb-4ce5-baaf-332521244eac)

There were two errors before that that I didn't pay attention to, and now I only find one log entry.
In addition, the current status is that I have already tried this feature and exceeded the maximum number of times.
V1.2.4
idea 2021.3.2
One of the mistakes,I'm not sure if the error has anything to do with Bito.

`kotlin.UninitializedPropertyAccessException: lateinit property globalStates has not been initialized
	at co.bito.intellij.completion.popup.PopupManager.getGlobalStates(PopupManager.kt:69)
	at co.bito.intellij.completion.actions.NextSuggestion.actionPerformed(NextSuggestion.kt:15)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:573)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:265)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:702)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:584)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:456)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:224)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:498)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

**Comment by nisha-bito** [comment]
hi @SMSshuai ,

Thanks for Reporting, we will look into it.

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @SMSshuai ,

The fix  for above issue is released along with Bito 1.2.6. Please install the new version and let us know if this is working fine for you.

Thanks,
Nisha

**Comment by SMSshuai** [comment]
> hi @SMSshuai ,
> 
> The fix for above issue is released along with Bito 1.2.6. Please install the new version and let us know if this is working fine for you.
> 
> Thanks, Nisha

It has been repaired and can be used normally

**Comment by nisha-bito** [comment]
great to hear @SMSshuai.
