### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.wm.ToolWindow.activate(java.lang.Runnable, boolean, boolean)" because the return value of "com.intellij.openapi.wm.ToolWindowManager.getToolWindow(String)" is null

### ISSUE THREAD

**Issue by hezhipengzipp** [gitbito/bitoai#197]
java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.wm.ToolWindow.activate(java.lang.Runnable, boolean, boolean)" because the return value of "com.intellij.openapi.wm.ToolWindowManager.getToolWindow(String)" is null
	at co.bito.intellij.actions.UpdateBito.actionPerformed(UpdateBito.java:66)
	at com.intellij.notification.NotificationAction.actionPerformed(NotificationAction.java:33)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
	at com.intellij.openapi.fileEditor.impl.IdeUiServiceImpl.performActionDumbAwareWithCallbacks(IdeUiServiceImpl.java:114)
	at com.intellij.notification.Notification.fire(Notification.java:283)
	at com.intellij.notification.impl.NotificationComponent.runAction(NotificationsToolWindow.kt:1177)
	at com.intellij.notification.impl.NotificationComponent.createAction$lambda$1(NotificationsToolWindow.kt:1089)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:175)
	at com.intellij.ui.components.labels.LinkLabel.doClick(LinkLabel.java:389)
	at com.intellij.ui.components.labels.LinkLabel$MyMouseHandler.mouseReleased(LinkLabel.java:362)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
	at java.desktop/java.awt.Component.processEvent(Component.java:6422)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4969)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4583)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4524)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2809)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:690)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:638)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:592)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:997)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:997)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

Android Studio Iguana | 2023.2.1
Build #AI-232.10227.8.2321.11479570, built on February 22, 2024
Runtime version: 17.0.9+0--11185874 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
    ide.browser.jcef.osr.enabled=false

Non-Bundled Plugins:
    com.intellij.ideolog (222.3.2.0)
    Dart (232.10305)
    co.bito.bito-intellij (1.3.0)
    com.bloc.intellij_generator_plugin (4.0.0)
    jclasslib (6.0.4.2)
    GsonFormatPlus (1.6.1)
    com.github.copilot (1.5.1.5285)
    io.flutter (78.4.1)

Bito version :1.3.0

**Comment by nisha-bito** [comment]
hi @hezhipengzipp ,

JetBrains API has released a new version of an API recently causing this exception. We are working with JB team to find the best option to implement the latest API as per JB guideline. 
We shall release a fix as soon as possible for this. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @hezhipengzipp ,

Looking at the logs, we see that you are using Android studio. In order to use Bito in Android studio, you need to enable JCEF browser, which is not enabled by default in Android studio but enabled in other JB IDE's. 

Please refer to document https://docs.bito.ai/support-and-questions/troubleshooting for more details and let us know if the error is resolved after enabling JCEF browser. 

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @hezhipengzipp ,
Please try to select diff version [17.0.9 xxxxx] and see if its working ? 

thanks,
Nisha

**Comment by hezhipengzipp** [comment]
version [17.0.9 xxxxx] it is ok ,but plugin Searching for bito only has this
![image](https://github.com/gitbito/bitoai/assets/19803305/7507e025-d1f3-4125-8632-e17782198a8f)

**Comment by hezhipengzipp** [comment]
![image](https://github.com/gitbito/bitoai/assets/19803305/11b6ad85-4416-48af-af7a-407b182bfb0a)

**Comment by hezhipengzipp** [comment]
![image](https://github.com/gitbito/bitoai/assets/19803305/a0051257-bef8-4a91-8e19-c5c738a379bf)
click setup not response

**Comment by hezhipengzipp** [comment]
![image](https://github.com/gitbito/bitoai/assets/19803305/2ff8b610-545b-46c1-b5b1-4fa8d9f53898)
I have selected version 17.0.9, but it still has no effect

**Comment by nisha-bito** [comment]
hi @hezhipengzipp ,

Can you please share the idea.log to further analysing this. 

In the mean time, please also see the suggestion/ workaround here for blank screens -https://docs.bito.ai/support-and-questions/troubleshooting#bito-doesnt-load-and-show-a-blank-page-when-installed-in-android-canary 

Thanks,
nisha

**Comment by hezhipengzipp** [comment]
[idea.log](https://github.com/gitbito/bitoai/files/15022047/idea.log)

**Comment by hezhipengzipp** [comment]
![image](https://github.com/gitbito/bitoai/assets/19803305/37175186-8a41-4521-a12d-b1331ef9dccd)
I can't enter my email address here.

**Comment by hezhipengzipp** [comment]
AndroidStudio .md file can't open @nisha-bito
