### ISSUE TITLE
Shortcuts do not work on IntelliJ IDEA Ultimate 2022.3.2

### ISSUE THREAD

**Issue by SwiftyWheels** [gitbito/bitoai#2]
Using IntelliJ IDEA Ultimate 2022.3.2.

Upon trying to use any shortcuts in the right-click menu, I receive an error. This occurs with any shortcut.

Here is the stacktrace for trying to use "Generate Comment" shortcut.

`
java.lang.StringIndexOutOfBoundsException: begin 32, end -1, length 43
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4604)
	at java.base/java.lang.String.substring(String.java:2707)
	at co.bito.intellij.services.GitUtilService.updateRepoInfoForGivenFile(GitUtilService.java:313)
	at co.bito.intellij.actions.GenerateComment$2.run(GenerateComment.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:429)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:480)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

**Comment by JcatZ13** [comment]
Same as above

**Comment by bitoandy** [comment]
This issue has been resolved in version [1.0.129 ](https://plugins.jetbrains.com/plugin/18289-bito-ai--use-chatgpt-to-write-code-fix-bugs-create-test-cases/versions/stable/285213). 
Please let us know if you are still seeing the issue.

**Comment by bitomukesh** [comment]
closing the issue as it is fixed in 1.0.129 build.
