### ISSUE TITLE
android studio 

### ISSUE THREAD

**Issue by RTException** [gitbito/bitoai#211]
On the latest version of Android Studio（Jellyfish | 2023.3.1 Patch 1）, the bito（1.3.2） plugin fails to run, and I have found the following error in the Android Studio's log:
`2024-05-26 22:31:00,750 [   1198]   WARN - #c.i.u.j.JBCefApp - JCefAppConfig.class is not from a JBR module, url: jar:file:/Applications/Android%20Studio.app/Contents/lib/lib.jar!/com/jetbrains/cef/JCefAppConfig.class (Use JBR bundled with the IDE)
2024-05-26 22:31:00,750 [   1198] SEVERE - #c.i.o.w.i.ToolWindowManagerImpl - Cannot process toolwindow Bito
com.intellij.diagnostic.PluginException: Cannot create class co.bito.intellij.webview.BitoWindowFactory (classloader=PluginClassLoader(plugin=PluginDescriptor(name=ChatGPT GPT-4 - Bito AI Code Assistant, id=co.bito.bito-intellij, descriptorPath=plugin.xml, path=~/Library/Application Support/Google/AndroidStudio2023.3/plugins/Bito-Jetbrains-PROD, version=1.3.2, package=null, isBundled=false), packagePrefix=null, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1401)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1377)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1426)
	at com.intellij.openapi.wm.ToolWindowEP.getToolWindowFactory(ToolWindowEP.java:114)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.beanToTask(ToolWindowSetInitializer.kt:280)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$beanToTask(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$2$1$1.invokeSuspend(ToolWindowSetInitializer.kt:312)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(Unknown Source)
	at com.intellij.serviceContainer.ComponentManagerImpl.findConstructorAndInstantiateClass(ComponentManagerImpl.kt:1383)
	at com.intellij.serviceContainer.ComponentManagerImpl.doInstantiateClass(ComponentManagerImpl.kt:1392)
	... 12 more
Caused by: java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:122)
	at co.bito.intellij.webview.BitoWindowFactory.<clinit>(BitoWindowFactory.java:18)
	... 16 more
2024-05-26 22:31:00,751 [   1199] SEVERE - #c.i.o.w.i.ToolWindowManagerImpl - Android Studio Jellyfish | 2023.3.1 Patch 1  Build #AI-233.14808.21.2331.11842104
2024-05-26 22:31:00,752 [   1200] SEVERE - #c.i.o.w.i.ToolWindowManagerImpl - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-05-26 22:31:00,752 [   1200] SEVERE - #c.i.o.w.i.ToolWindowManagerImpl - OS: Mac OS X
2024-05-26 22:31:00,752 [   1200] SEVERE - #c.i.o.w.i.ToolWindowManagerImpl - Plugin to blame: ChatGPT GPT-4 - Bito AI Code Assistant version: 1.3.2`

**Comment by RTException** [comment]
And, I attempted to change the runtime of Android Studio to a version that supports JCEF (e.g., jbr_jcef-17.0.10-osx-aarch64-b1087.23), but after the modification, Android Studio crashed upon restart.

**Comment by nisha-bito** [comment]
hi @RTException 

Please go through document https://docs.bito.ai/support-and-questions/troubleshooting and make the settings accordingly to make Bito work in Android Studio. 

Please note about two settings for Android studio-
1. https://docs.bito.ai/support-and-questions/troubleshooting#id-1-bito-jetbrain-extension-doesnt-work-in-android-studio
2. https://docs.bito.ai/support-and-questions/troubleshooting#bito-doesnt-load-and-show-a-blank-page-when-installed-in-android-canary

Also, In dropdown you get multiple options of Runtime with JCEF supported, please try to select some other option, if the latest one is not working. 

If you face any further issue, do let us know.

Thanks,
Nisha

**Comment by RTException** [comment]
Thank U, @nisha-bito.After modifying the runtime and `ide.browser.jcef.sandbox.enable=disable`, it can run normally.
