### ISSUE TITLE
Doesn't work in Android Studio Electric Eel | 2022.1.1 Patch 1

### ISSUE THREAD

**Issue by Razorkrawzer** [gitbito/bitoai#4]
Exception in plugin **Bito AI - Use ChatGPT to write code, fix bugs, create test cases (1.0.129)**

com.intellij.diagnostic.PluginException: Cannot init toolwindow co.bito.intellij.webview.BitoWindowFactory@64b70df9 [Plugin: co.bito.bito-intellij]
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows(ToolWindowSetInitializer.kt:194)
	at com.intellij.toolWindow.ToolWindowSetInitializer.access$createAndLayoutToolWindows(ToolWindowSetInitializer.kt:83)
	at com.intellij.toolWindow.ToolWindowSetInitializer$initUi$1.accept(ToolWindowSetInitializer.kt:147)
	at com.intellij.toolWindow.ToolWindowSetInitializer$initUi$1.accept(ToolWindowSetInitializer.kt:83)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:714)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at com.intellij.toolWindow.ToolWindowSetInitializer$initUi$2.execute(ToolWindowSetInitializer.kt:156)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:750)
	at java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)
	at java.base/java.util.concurrent.CompletableFuture.thenAcceptAsync(CompletableFuture.java:2117)
	at com.intellij.toolWindow.ToolWindowSetInitializer.initUi(ToolWindowSetInitializer.kt:141)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doInit(ToolWindowManagerImpl.kt:446)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.init(ToolWindowManagerImpl.kt:419)
	at com.intellij.toolWindow.InitToolWindowSetActivity$runActivity$2.run(ToolWindowSetInitializer.kt:72)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:252)
	at com.intellij.ui.jcef.JBCefBrowserBase.lambda$new$3(JBCefBrowserBase.java:152)
	at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:127)
	at com.intellij.ui.jcef.JBCefBrowserBase.<init>(JBCefBrowserBase.java:152)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:190)
	at com.intellij.ui.jcef.JBCefBrowser.<init>(JBCefBrowser.java:150)
	at co.bito.intellij.windows.BitoWindow.webViewLazy(BitoWindow.java:33)
	at co.bito.intellij.windows.BitoWindow.webView(BitoWindow.java:51)
	at co.bito.intellij.windows.BitoWindow.content(BitoWindow.java:55)
	at co.bito.intellij.webview.BitoWindowFactory.createToolWindowContent(BitoWindowFactory.java:29)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:529)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:508)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:921)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:861)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:850)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1025)
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows(ToolWindowSetInitializer.kt:188)
	... 44 more
![image](https://user-images.githubusercontent.com/23465469/216699660-ead18fa0-0293-41fd-90a4-2b8d6feb0eca.png)

**Comment by bitomukesh** [comment]
Thanks for reporting this. We are investigating this, and a fix will be available soon. Unfortunately, Android studio extensions work a bit differently from the rest of IntelliJ IDEs. We need to fix the compatibility.

**Comment by bitoandy** [comment]
Hi @Razorkrawzer ,

Bito plugin/extension needs support for JCEF browser, which is not included in Android Studio due to its default boot runtime setup. You can change the default Boot runtime settings in Android Studio to a version which supports JCEF browser and get Bito running on Android Studio

Given below are instructions to change the default boot runtime settings:
1. Go to Help → Find action
2. Type → “[Choose Boot Java Runtime for the IDE](https://i.imgur.com/iAwt6b9.png)”
3. From the dropdown “New”, select a Boot runtime which support JCEF browser.
4. Select ok and restart.

Once done install Bito and you will have it up and running.
Here’s the link to loom video showing the whole process: https://www.loom.com/share/4c27a38758da464a93505f86e7a08f29

Please try it out and let us know if you face any issues.

**Comment by Razorkrawzer** [comment]
Thank you! I followed the steps and it works

**Comment by nisha-bito** [comment]
hi @Razorkrawzer ,

Based on what version of Java you are using, you will get multiple options to select from the Runtime environment which supports JCEF browser. You may want to try to select a different option to make it work.

Example -
![image](https://github.com/gitbito/bitoai/assets/123052606/27e35b86-c4f5-412c-9408-8e8994dc6d93)

Thanks,
Nisha

**Comment by nisha-bito** [comment]
hi @Razorkrawzer ,

Closing this ticket, however you can always re-open the ticket or create a new ticket if you face any further issue.

Thanks,
Nisha

**Comment by jingxinli33** [comment]
Hello, I am also a plugin developer and I've come across the same issue with JCFF not working in Android Studio. Could you please kindly share any alternative solutions or techniques you may have used to address this problem, without switching the runtime? Your assistance would be greatly appreciated.

**Comment by nisha-bito** [comment]
hi @jingxinli33 ,

Bito needs JCEF browser to run the plugin.
To run Bito, the only possible way in Android is to choose the runtime which support JCEF.  There are multiple runtime available with jcef, you may want to try selecting one of them to enable JCEF.


Thanks,
Nisha

**Comment by voghDev** [comment]
The same thing happening here. After selecting a runtime with JCEF, the error was gone when enabling the Bito plugin, but even with no errors, I can't see the Bito tab on the right menu ([the one on this video](https://www.youtube.com/watch?v=3SawgoqsviY)).

I'm using Android Studio Flamingo | 2022.2.1

**Comment by nisha-bito** [comment]
@voghDev ,

Can you try to choose some other runtime with JCEF support and check ? 

Thanks,
Nisha

**Comment by voghDev** [comment]
Hi Nisha, thanks for the response.

![image](https://github.com/gitbito/bitoai/assets/4963568/912b97da-f2d4-4502-97db-cf28f24509cc)

It seems that I only have one runtime available. there are multiple entries, but all of them seem to be the same one.
Should I install a different runtime? I haven't done that earlier

**Comment by nisha-bito** [comment]
hi @voghDev ,

Can you please share idea logs to further analyze this ? 

Thanks,
Nisha

**Comment by voghDev** [comment]
Sure @nisha-bito ! The error I'm getting is pretty similar to the one described in the Title of this issue. I'll attach a small piece of the `idea.log` file. In case you need more detail, I can send you the entire file via email or any details you require.
Here's the log 👇 

```
com.intellij.diagnostic.PluginException: Cannot create class co.bito.intellij.webview.BitoWindowFactory (classloader=PluginClassLoader(plugin=PluginDescriptor(name=ChatGPT GPT-4 - Bito AI Code Assistant, id=co.bito.bito-intellij, descriptorPath=plugin.xml, path=~\AppData\Roaming\Google\AndroidStudio2022.2\plugins\Bito-Jetbrains-PROD, version=1.1.8, package=null, isBundled=false), packagePrefix=null, instanceId=111, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:883)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:900)
	... Enormous Stacktrace that I could attach in case you need
	at com.intellij.ide.plugins.DynamicPlugins.loadPlugin(DynamicPlugins.kt:833)
	... Enormous Stacktrace that I could attach in case you need
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:489)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:478)
        ... More stack trace
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:520)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:844)
	... 109 more
Caused by: java.lang.IllegalStateException: JCEF is not supported in this env or failed to initialize
	at com.intellij.ui.jcef.JBCefApp.getInstance(JBCefApp.java:252)
	at co.bito.intellij.webview.BitoWindowFactory.<clinit>(BitoWindowFactory.java:18)
	... 112 more
2023-10-17 11:52:21,792 [7795769] SEVERE - #c.i.o.e.i.ExtensionPointImpl - Android Studio Flamingo | 2022.2.1 Patch 2  Build #AI-222.4459.24.2221.10121639
2023-10-17 11:52:21,792 [7795769] SEVERE - #c.i.o.e.i.ExtensionPointImpl - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-10-17 11:52:21,792 [7795769] SEVERE - #c.i.o.e.i.ExtensionPointImpl - OS: Windows 10
2023-10-17 11:52:21,792 [7795769] SEVERE - #c.i.o.e.i.ExtensionPointImpl - Plugin to blame: ChatGPT GPT-4 - Bito AI Code Assistant version: 1.1.8
2023-10-17 11:52:21,793 [7795770]   INFO - #c.i.i.p.DynamicPlugins - Plugin co.bito.bito-intellij loaded without restart in 142 ms
2023-10-17 11:52:21,794 [7795771]   WARN - #c.i.c.ComponentStoreImpl - Duplicated scheme IntelliJ Light - old: IntelliJ Light, new IntelliJ Light
... Other traces that seem not related to this
2023-10-17 11:52:21,925 [7795902]   INFO - #c.i.u.i.FileBasedIndexImpl - Indices to be built:FilenameIndex(v = 258)
2023-10-17 11:52:21,926 [7795903]   INFO - c.i.u.i.FileBasedIndexDataInitialization - Index data initialization done: 128 ms. Initialized indexes: [FilenameIndex, FrameworkDetectionIndex, TodoIndex, IdIndex, filetypes, Stubs, Trigram.Index, fileIncludes, DomFileIndex, RelaxSymbolIndex, XmlTagNames, XmlNamespaces, html5.custom.attributes.index, SchemaTypeInheritance, json.file.root.values, yaml.keys.name, editorconfig.index.name, xmlProperties, bytecodeAnalysis, java.auto.module.name, java.source.module.name, java.null.method.argument, java.fun.expression, java.binary.plus.expression, org.jetbrains.kotlin.idea.versions.KotlinJvmMetadataVersionIndex, org.jetbrains.kotlin.idea.versions.KotlinJsMetadataVersionIndex, org.jetbrains.kotlin.idea.vfilefinder.KotlinPartialPackageNamesIndex, org.jetbrains.kotlin.idea.vfilefinder.KotlinClassFileIndex, org.jetbrains.kotlin.idea.vfilefinder.KotlinJavaScriptMetaFileIndex, org.jetbrains.kotlin.idea.vfilefinder.KotlinMetadataFileIndex, org.jetbrains.kotlin.idea.vfilefinder.KotlinMetadataFilePackageIndex, org.jetbrains.kotlin.idea.vfilefinder.KotlinModuleMappingIndex, org.jetbrains.kotlin.idea.vfilefinder.KotlinPackageSourcesMemberNamesIndex, org.jetbrains.kotlin.idea.vfilefinder.KotlinJvmModuleAnnotationsIndex, org.jetbrains.kotlin.idea.vfilefinder.KotlinBuiltInsMetadataIndex, org.jetbrains.kotlin.idea.vfilefinder.KotlinStdlibIndex, org.jetbrains.kotlin.idea.vfilefinder.KlibMetaFileIndex, FileNameWithoutExtensionIndex, IdeaPluginRegistrationIndex, PluginIdModuleIndex, PluginIdDependenciesIndex, devkit.ExtensionPointIndex, devkit.ExtensionPointClassIndex, com.android.tools.idea.model.AndroidManifestIndex$Companion$NAME$1.NAME, BindingXmlIndex, NavXmlIndex, android.ndk.jni.nativemethodindex].
2023-10-17 11:52:21,927 [7795904]   INFO - #c.i.u.i.UnindexedFilesUpdater - Started scanning for indexing of xxxx-android. Reason: Plugin loaded/unloaded
2023-10-17 11:52:21,927 [7795904]   INFO - #c.i.u.i.UnindexedFilesUpdater - Performing delayed pushing properties tasks for xxxx-android took 0ms; general responsiveness: ok; EDT responsiveness: ok
2023-10-17 11:52:21,933 [7795910]   INFO - #c.i.u.i.UnindexedFilesUpdater - Scanning of xxxx-android uses 23 scanning threads
2023-10-17 11:52:21,987 [7795964]   INFO - c.i.p.s.StubIndexImpl$StubIndexInitialization - Index data initialization done: 61 ms. Initialized stub indexes: {org.jetbrains.kotlin.idea.stubindex.KotlinProbablyNothingFunctionShortNameIndex, gr.class.super, gr.annot.members, org.jetbrains.kotlin.idea.stubindex.KotlinTopLevelClassByPackageIndex, org.jetbrains.kotlin.idea.stubindex.KotlinFullClassNameIndex, dom.namespaceKey, org.jetbrains.kotlin.idea.stubindex.KotlinFunctionShortNameIndex, org.jetbrains.kotlin.idea.stubindex.KotlinInnerTypeAliasClassIdIndex, java.field.name, org.jetbrains.kotlin.idea.stubindex.KotlinProbablyContractedFunctionShortNameIndex, jvm.static.member.name, org.jetbrains.kotlin.idea.stubindex.KotlinTopLevelTypeAliasByPackageIndex, org.jetbrains.kotlin.idea.stubindex.KotlinOverridableInternalMembersShortNameIndex, org.jetbrains.kotlin.idea.stubindex.KotlinExtensionsInObjectsByReceiverTypeIndex, gr.method.name, jvm.static.member.type, java.annotations, java.module.name, org.jetbrains.kotlin.idea.stubindex.KotlinFilePartClassIndex, org.jetbrains.kotlin.idea.stubindex.KotlinJvmNameAnnotationIndex, java.method.name, gr.anonymous.class, kotlin.primeIndexKey, org.jetbrains.kotlin.idea.stubindex.KotlinMultifileClassPartIndex, java.anonymous.baseref, gr.annot.method.name, org.jetbrains.kotlin.idea.stubindex.KotlinFileFacadeClassByPackageIndex, markdown.header, org.jetbrains.kotlin.idea.stubindex.KotlinTypeAliasShortNameIndex, org.jetbrains.kotlin.idea.stubindex.KotlinExactPackagesIndex, org.jetbrains.kotlin.idea.stubindex.KotlinScriptFqnIndex, properties.index, org.jetbrains.kotlin.idea.stubindex.KotlinTopLevelPropertyByPackageIndex, org.jetbrains.kotlin.idea.stubindex.KotlinFileFacadeShortNameIndex, gr.class.fqn, org.jetbrains.kotlin.idea.stubindex.KotlinClassShortNameIndex, org.jetbrains.kotlin.idea.stubindex.KotlinTopLevelExtensionsByReceiverTypeIndex, org.jetbrains.kotlin.idea.stubindex.KotlinTopLevelFunctionByPackageIndex, org.jetbrains.kotlin.idea.stubindex.KotlinProbablyNothingPropertyShortNameIndex, org.jetbrains.kotlin.idea.stubindex.KotlinSuperClassIndex, java.class.fqn, gr.field.name, org.jetbrains.kotlin.idea.stubindex.KotlinTopLevelTypeAliasFqNameIndex, gr.script.class, dom.elementClass, org.jetbrains.kotlin.idea.stubindex.KotlinPropertyShortNameIndex, java.class.extlist, org.jetbrains.kotlin.idea.stubindex.KotlinTypeAliasByExpansionShortNameIndex, org.jetbrains.kotlin.idea.stubindex.KotlinTopLevelPropertyFqnNameIndex, gr.script.fqn, java.class.shortname, org.jetbrains.kotlin.idea.stubindex.KotlinAnnotationsIndex, org.jetbrains.kotlin.idea.stubindex.KotlinFileFacadeFqNameIndex, org.jetbrains.kotlin.idea.stubindex.KotlinTopLevelFunctionFqnNameIndex, java.method.parameter.types, org.jetbrains.kotlin.idea.stubindex.KotlinSubclassObjectNameIndex}.
2023-10-17 11:52:22,289 [7796266]   INFO - #c.a.t.i.u.SdkComponentSource - Downloading https://dl.google.com/android/repository/addons_list-5.xml
2023-10-17 11:52:22,377 [7796354]   WARN - #c.i.o.o.e.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager
2023-10-17 11:52:22,404 [7796381]   INFO - #c.a.t.i.u.SdkComponentSource - Downloading https://dl.google.com/android/repository/repository2-3.xml
2023-10-17 11:52:22,404 [7796381]   INFO - #c.a.t.i.u.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android/sys-img2-3.xml
2023-10-17 11:52:22,
```

**Comment by Ahmed-Muhammad** [comment]
> Hi @Razorkrawzer ,
> 
> Bito plugin/extension needs support for JCEF browser, which is not included in Android Studio due to its default boot runtime setup. You can change the default Boot runtime settings in Android Studio to a version which supports JCEF browser and get Bito running on Android Studio
> 
> Given below are instructions to change the default boot runtime settings:
> 
> 1. Go to Help → Find action
> 2. Type → “[Choose Boot Java Runtime for the IDE](https://i.imgur.com/iAwt6b9.png)”
> 3. From the dropdown “New”, select a Boot runtime which support JCEF browser.
> 4. Select ok and restart.
> 
> Once done install Bito and you will have it up and running. Here’s the link to loom video showing the whole process: https://www.loom.com/share/4c27a38758da464a93505f86e7a08f29
> 
> Please try it out and let us know if you face any issues.


its worked for me, Thank you very much.
